github: [Carlo39-coder]

# Optional – nur wenn du die Accounts wirklich hast und live sind
# ko_fi: carlo39coder
# buy_me_a_coffee: carlo39

custom:
  - "https://paypal.me/Carlo39Coder"   # ← erstelle den echten Link, wenn noch nicht da
  # - "https://jumper-music-eval-1.onrender.com/donate"  # für später
